### ISSUE TITLE
后端运行起来了，web前端的哪个地址怎么填写

### ISSUE THREAD

**Issue by vercen** [celesWuff/ktpwarp-web#1]

**Comment by vercen** [comment]
![image](https://user-images.githubusercontent.com/70558042/224887201-16022930-2ea5-4505-8995-253f2962f631.png)
![image](https://user-images.githubusercontent.com/70558042/224887228-d713d498-50a2-43fe-8e06-78f7f089c8d7.png)

**Comment by celesWuff** [comment]
开启 TLS： `wss://域名:端口/路径`
不开启 TLS： `ws://域名:端口/路径`
